import { Video, AnalysisNode, AnalysisReport } from "./types";

export const generateMockNodes = (duration: number = 180): AnalysisNode[] => {
  return [
    {
      id: "node-1",
      startSec: 0,
      endSec: Math.min(15, duration),
      title: "Hook: Catchy Introduction",
      nodeTypes: ["shot_change", "info_point"],
      shotDescription: "Close up of the host looking excited, holding a mysterious object.",
      visualElements: ["Host face", "Mysterious black box", "Studio lighting"],
      audioElements: ["Upbeat intro music", "Host speaking loudly: 'You won't believe what's inside!'"],
      editIntent: "Grab viewer's attention immediately within the first 3 seconds.",
      emotionLabel: "Excitement",
      emotionIntensity: 8,
      narrativeFunction: "Hook",
      confidence: 0.95,
      isHighlight: true,
      note: "Great hook, consider using this clip for trailer.",
      methodologyTags: [
        {
          ruleId: "R-HOOK-001",
          ruleName: "黄金 3 秒钩子",
          category: "hook",
          status: "hit",
          evidence: "开场 0-3s 用神秘箱 + 主持人放大表情 + '你绝对想不到里面是什么' 三层同步",
          confidence: 0.9,
        },
      ],
    },
    {
      id: "node-2",
      startSec: Math.min(15, duration),
      endSec: Math.min(45, duration),
      title: "Context: Explaining the premise",
      nodeTypes: ["info_point", "emotion_turn"],
      shotDescription: "Medium shot of host sitting at a table, explaining the back story.",
      visualElements: ["Table", "Graphs overlay"],
      audioElements: ["Music volume drops", "Host voiceover explaining stats"],
      editIntent: "Provide necessary background context for the climax.",
      emotionLabel: "Curiosity",
      emotionIntensity: 5,
      narrativeFunction: "Development",
      confidence: 0.88,
      isHighlight: false,
      methodologyTags: [
        {
          ruleId: "R-PACE-001",
          ruleName: "镜头长短交替",
          category: "pacing",
          status: "violation",
          evidence: "15-45s 全部是中景 4s+ 的长镜头，缺少短切作信息密度",
          confidence: 0.75,
          fixSuggestion: "在 development 段插入 2-3 个 1-2s 的图表/数据短切",
        },
      ],
    },
    {
      id: "node-3",
      startSec: Math.min(45, duration),
      endSec: Math.min(120, duration),
      title: "The Reveal: Opening the box",
      nodeTypes: ["shot_change", "emotion_turn", "audio_change"],
      shotDescription: "Quick cuts between host's face and the object inside the box.",
      visualElements: ["Glowing object", "Host wide eyes"],
      audioElements: ["Suspenseful riser", "Whoosh sound effects"],
      editIntent: "Build suspense and deliver the payoff.",
      emotionLabel: "Surprise",
      emotionIntensity: 9,
      narrativeFunction: "Climax",
      confidence: 0.92,
      isHighlight: true,
      methodologyTags: [
        {
          ruleId: "R-PACE-002",
          ruleName: "节奏与情绪匹配",
          category: "pacing",
          status: "hit",
          evidence: "高潮段大量 1-2s 快切配合 riser 音效，节奏与情绪同步上升",
          confidence: 0.88,
        },
        {
          ruleId: "R-SOUND-001",
          ruleName: "BGM 节拍同步",
          category: "sound",
          status: "hit",
          evidence: "切点准确落在 riser 音效的爆点上",
          confidence: 0.82,
        },
      ],
    },
    {
      id: "node-4",
      startSec: Math.min(120, duration),
      endSec: duration,
      title: "Call to Action / Outro",
      nodeTypes: ["edit_intent", "audio_change"],
      shotDescription: "Host points to the screen, text overlay 'Subscribe'.",
      visualElements: ["Subscribe button graphic", "Host smiling"],
      audioElements: ["Outro music starts", "Host: 'Like and subscribe for more'"],
      editIntent: "Convert viewers to subscribers and drive engagement.",
      emotionLabel: "Friendly",
      emotionIntensity: 6,
      narrativeFunction: "Ending",
      confidence: 0.90,
      isHighlight: false,
      methodologyTags: [
        {
          ruleId: "R-COMPLETE-001",
          ruleName: "结尾回收",
          category: "completion",
          status: "hit",
          evidence: "结尾给出明确 CTA + Subscribe 字幕，配 outro 音乐",
          confidence: 0.86,
        },
      ],
    }
  ];
};

export const generateMockReport = (): AnalysisReport => {
  return {
    summary: "This video utilizes a textbook high-retention structure, starting with a strong hook and delivering a payoff exactly at the 60% mark. Emotion builds steadily towards the climax.",
    structure: {
      hook: "0-15s: High energy intro with mystery box.",
      development: "15-45s: Context building using B-roll and graphics.",
      turn: "45-50s: Suspense building sequence before box opens.",
      climax: "50-120s: The reveal and reaction.",
      ending: "120s+: Standard CTA and wrap-up."
    },
    pacing: "Fast-paced intro (avg shot length 1.2s), slowing down during development (avg shot 4s), and accelerating again during the climax.",
    editingStyle: "Dynamic vlog style with frequent punch-ins and sound effect stingers for emphasis.",
    composition: "Primarily medium close-ups optimized for mobile viewing, with text placed in the safe zones.",
    takeaways: [
      "Use physical props to create curiosity gaps in the hook.",
      "Don't let the development phase drag; punctuate with graphics.",
      "Match audio riser intensity with cut frequency."
    ],
    methodologyAudit: {
      detectedGenre: "review",
      lengthBucket: "long",
      appliedRuleSets: ["_common", "length/long", "genre/review"],
      genreConfidence: 0.86,
      overallScore: 74,
      hits: [
        {
          ruleId: "R-HOOK-001",
          ruleName: "黄金 3 秒钩子",
          category: "hook",
          status: "hit",
          evidence: "开场 0-3s 用神秘箱 + 主持人放大表情 + '你绝对想不到里面是什么' 三层同步",
          confidence: 0.9,
        },
        {
          ruleId: "R-PACE-002",
          ruleName: "节奏与情绪匹配",
          category: "pacing",
          status: "hit",
          evidence: "高潮段大量 1-2s 快切配合 riser 音效",
          confidence: 0.88,
        },
        {
          ruleId: "R-SOUND-001",
          ruleName: "BGM 节拍同步",
          category: "sound",
          status: "hit",
          evidence: "切点准确落在 riser 音效的爆点上",
          confidence: 0.82,
        },
        {
          ruleId: "R-COMPLETE-001",
          ruleName: "结尾回收",
          category: "completion",
          status: "hit",
          evidence: "结尾给出明确 CTA + Subscribe 字幕",
          confidence: 0.86,
        },
      ],
      violations: [
        {
          ruleId: "R-PACE-001",
          ruleName: "镜头长短交替",
          category: "pacing",
          status: "violation",
          evidence: "15-45s 全部是中景 4s+ 的长镜头，缺少短切作信息密度",
          confidence: 0.75,
          fixSuggestion: "在 development 段插入 2-3 个 1-2s 的图表/数据短切",
        },
      ],
      misses: [
        {
          ruleId: "R-REVIEW-006",
          ruleName: "横向对比",
          category: "structure",
          expectedAt: "测评中后段",
          reason: "全片只讲了一个产品，没有任何与竞品/旧款的对比镜头或参数表",
          fixSuggestion: "在 60-90s 之间插入一段与同价位竞品的横向对比",
        },
        {
          ruleId: "R-LONG-004",
          ruleName: "中段缓冲段",
          category: "structure",
          expectedAt: "约 50% 位置（90-120s）",
          reason: "信息密度从头压到尾，中段没有故事 / 幽默缓冲",
          fixSuggestion: "在 90-120s 加入一段使用场景模拟或主创小故事，给观众喘息",
        },
      ],
    },
  };
};
